service: go-serverless-gatway-ehsansepehri
frameworkVersion: '>=1.28.8'
provider: 
  name: aws
  runtime: go1.x
  region: eu-north-1

functions:
  api:
    handler: bin/main

package:
  patterns:
    - '!*/**'
    - bin/main
