service: go-serverless-gatway-ehsansepehri
frameworkVersion: '>=1.28.8'
provider: 
  name: aws
  runtime: go1.x
  region: eu-north-1

functions:
  api:
    handler: bin/main

resources:
  Resources:
    devices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: devices_ehsansepehri
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
          
package:
  patterns:
    - '!*/**'
    - bin/main
